version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
  
  test:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - run:
          name: npm test:ci
          command: npm test:ci

workflows:
  build-and-test:
    jobs:
      - build
      - test