version: 2.1

jobs:
  install-and-test:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - run:
          name: install and test
          command: ｜
            npm install
            npm run test:ci
  
workflows:
  install-test:
    jobs:
      - install-and-test
